### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by gowerc** [keiras/keiras.github.io#1]
Heya,

found your report and it was an interesting read thank you! Just want to say that depending on how you’ve derived it you made need to be careful with this remark:

> The population of players playing both solo and team modes seems to be the core in terms of longevity and stability of the game

I can’t help but feel the results you are seeing are likely due to immortal time bias, I.e. players have to have stayed in the game longer on average to have played multiple game types which therefore leads to the multiple game type players appear to have higher retention. Typically to combat this you would do a landmark assessment where you categories people at say day 10 and then look at their survival after this point (ignoring days 0-10). 

Anyway thank you for your work!

**Comment by keiras** [comment]
Thanks for the comment and pointers on the stats keywords Immortal time bias and landmark assessment. I felt wrong when constructing this chart but I couldn't properly name the issue so my search for the solutions was fruitless. 

Looking back, I agree the bias is present for sure. The labeling of groups were done simply by seeing total sums of games played in the period per game mode. If there were 0 in 1v1s, they would be "team", if there were 0 in 2v2, 3v3, 4v4 they would be "solo", otherwise "mixed". 

I have tried to make the chart less wrong by changing the definition of "mixed". I newly consider only accounts that have placed into both 1v1 and some teammode in their first week of multiplayer (that is ~40% of the previous mixed population). I consider the later date as the enrollment date. This should make the numbers comparable with the exclusive groups. 

I might try doing the 10d landmark assessment later to see how it affects the lines. This calculation would require more changes in the data flow, so I opt for the other approach for now. 



Also the mentioned remark was out of place even if the chart was without bias :)
